name: charify
description: A charity crowdfunding application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
  google_maps_flutter: ^2.0.1
  firebase_core:
  firebase_auth:
  razorpay_flutter:
  fluttertoast:
  google_fonts:
  animations:
  cupertino_icons:
  flutterwave:
  flutter_svg:
  webview_flutter:
  flutter_webview_plugin: ^0.4.0
  desktop_webview_window:
  fwfh_webview:
  flutter_widget_from_html_core:
  # flutter_inappwebview: ^5.7.2
  # flutterwave_standard: 1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.3.3
  

flutter_icon:
  android: true
  ios: true
  image_path: 'images/charify_logo.png'

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/icons/

  fonts:
    - family: Dancing Script
      fonts:
        - asset: fonts/DancingScript-Bold.ttf